CREATE DATABASE IF NOT EXISTS ForumDB;
USE ForumDB;

-- Bảng Vai Trò
CREATE TABLE VAITRO (
    MaVT INT PRIMARY KEY,
    TenVT VARCHAR(100) NOT NULL
);

-- Bảng Người Dùng
CREATE TABLE NGUOIDUNG (
    MaND INT PRIMARY KEY,
    TenND VARCHAR(100) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    NgayTaoTK DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaVT INT,
    FOREIGN KEY (MaVT) REFERENCES VAITRO(MaVT)
);

-- Bảng Bài Viết
CREATE TABLE BAIVIET (
    MaBV INT PRIMARY KEY,
    TenBV VARCHAR(255) NOT NULL,
    NoiDungBV TEXT NOT NULL,
    NgayTaoBV DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhapBV DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    MaND INT,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

-- Bảng Danh Mục
CREATE TABLE DANHMUC (
    MaDM INT PRIMARY KEY,
    TenDM VARCHAR(100) NOT NULL,
    MaBV INT,
    FOREIGN KEY (MaBV) REFERENCES BAIVIET(MaBV)
);

-- Bảng Bình Luận
CREATE TABLE BINHLUAN (
    MaBL INT PRIMARY KEY,
    NoiDungBL TEXT NOT NULL,
    ThoiGianBL DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaND INT,
    MaBV INT,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaBV) REFERENCES BAIVIET(MaBV)
);

-- Bảng Lượt Thích
CREATE TABLE LUOTTHICH (
    MaLT INT PRIMARY KEY,
    ThoiGian DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaND INT,
    MaBV INT,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND),
    FOREIGN KEY (MaBV) REFERENCES BAIVIET(MaBV)
);

-- Bảng Thông Báo
CREATE TABLE THONGBAO (
    MaTB INT PRIMARY KEY,
    NoiDungTB TEXT NOT NULL,
    ThoiGianTB DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaND INT,
    FOREIGN KEY (MaND) REFERENCES NGUOIDUNG(MaND)
);

-- Bảng Thẻ
CREATE TABLE THE (
    MaThe INT PRIMARY KEY,
    TenThe VARCHAR(100) NOT NULL
);

-- Bảng Quan Hệ Bài Viết - Thẻ
CREATE TABLE CTLK (
    MaBV INT,
    MaThe INT,
    PRIMARY KEY (MaBV, MaThe),
    FOREIGN KEY (MaBV) REFERENCES BAIVIET(MaBV),
    FOREIGN KEY (MaThe) REFERENCES THE(MaThe)
);
